/*
 * GOAT Arena 첫 운영월에 반드시 실측할 지표와 현재 시뮬레이션 가정입니다.
 * initialAssumption은 정책 확정값이 아니며, 첫 달 관측값으로 교체할 대상입니다.
 */
const FIRST_MONTH_METRICS = Object.freeze([
  {
    key: "payment.successful_count",
    label: "학습권 패키지 승인 결제 건수",
    unit: "count",
    category: "payment",
  },
  {
    key: "payment.net_approved_amount",
    label: "학습권 패키지 유효 승인 금액",
    unit: "won",
    category: "payment",
  },
  {
    key: "payment.refund_cancel_rate",
    label: "학습권 패키지 환불·취소 비율",
    unit: "percent",
    category: "payment",
  },
  {
    key: "access.zero_balance_rate",
    label: "정기권 학습 가능 일수 0일 도달 비율",
    unit: "percent",
    category: "access-cycle",
  },
  {
    key: "access.average_depletion_day",
    label: "정기권 학습 가능 일수 평균 소진 일차",
    unit: "day",
    category: "access-cycle",
  },
  {
    key: "access.first_use_before_20_share",
    label: "첫 이용 20시 이전 비율",
    unit: "percent",
    category: "access-cycle",
  },
  {
    key: "access.first_use_after_20_share",
    label: "첫 이용 20시 이후 비율",
    unit: "percent",
    category: "access-cycle",
  },
  {
    key: "access.first_use_before_20_conversion_rate",
    label: "20시 이전 첫 이용자의 결제·활성 전환율",
    unit: "percent",
    category: "conversion",
  },
  {
    key: "access.first_use_after_20_conversion_rate",
    label: "20시 이후 첫 이용자의 결제·활성 전환율",
    unit: "percent",
    category: "conversion",
  },
  {
    key: "access.first_day_deduction_support_rate",
    label: "첫날 차감 관련 문의율",
    unit: "percent",
    category: "support",
  },
  {
    key: "conversion.payment_view_to_purchase",
    label: "결제 화면 진입 대비 결제 전환율",
    unit: "percent",
    category: "conversion",
  },
  {
    key: "renewal.within_24h_rate",
    label: "만료 후 24시간 내 재구매율",
    unit: "percent",
    category: "renewal",
  },
  {
    key: "renewal.within_72h_rate",
    label: "만료 후 72시간 내 재구매율",
    unit: "percent",
    category: "renewal",
  },
  {
    key: "renewal.late_rate",
    label: "72시간 이후 재구매율",
    unit: "percent",
    category: "renewal",
  },
  {
    key: "renewal.assessment_completion_rate",
    label: "랭크 탈환 배치고사 완료율",
    unit: "percent",
    category: "renewal",
  },
  {
    key: "renewal.assessment_dropoff_rate",
    label: "랭크 탈환 배치고사 이탈률",
    unit: "percent",
    category: "renewal",
  },
  {
    key: "renewal.late_success_rate",
    label: "72시간 이후 재구매 복귀 성공률",
    unit: "percent",
    category: "renewal",
  },
  {
    key: "main.expiry_to_sub_rate",
    label: "Ranked 만료 후 Unranked 강등 비율",
    unit: "percent",
    category: "division",
  },
  {
    key: "main.expiry_to_sub_tier_distribution",
    label: "Ranked 만료 후 Unranked 배치 티어 분포",
    unit: "count",
    category: "division",
    dimensions: ["tier"],
  },
  {
    key: "main.entry_learning_days_distribution",
    label: "Ranked 진입 시작 학습일수 분포",
    unit: "count",
    category: "main-division",
    dimensions: ["learningDayBucket"],
  },
  {
    key: "main.average_active_days_before_demotion",
    label: "Ranked 진입 후 강등까지 평균 활동 일수",
    unit: "day",
    category: "main-division",
  },
  {
    key: "main.upward_match_request_success_rate",
    label: "Ranked 상향 쟁탈전 요청 대비 성립률",
    unit: "percent",
    category: "main-match-liquidity",
    dimensions: ["sourceTier", "targetTier", "tierGap"],
  },
  {
    key: "main.stake_days_distribution",
    label: "Ranked 경기 예치 학습일수 분포",
    unit: "count",
    category: "main-economy",
    dimensions: ["matchType", "tierGap", "stakeDays"],
  },
  {
    key: "main.invitation_acceptance_rate",
    label: "Ranked 하위 티어 초대 수락률",
    unit: "percent",
    category: "main-invitation",
    dimensions: ["sourceTier", "targetTier", "tierGap"],
  },
  {
    key: "main.invitation_response_time",
    label: "Ranked 하위 티어 초대 평균 응답 시간",
    unit: "minute",
    category: "main-invitation",
    dimensions: ["result"],
  },
  {
    key: "main.invitation_reselection_count",
    label: "Ranked 초대 1건당 후보 재선정 횟수",
    unit: "count",
    category: "main-invitation",
  },
  {
    key: "main.invitation_release_reason_distribution",
    label: "Ranked 초대 예약 학습일수 해제 사유 분포",
    unit: "count",
    category: "main-invitation",
    dimensions: ["reasonCode"],
  },
  {
    key: "main.learning_day_net_transfer_distribution",
    label: "Ranked 사용자별 경기 학습일수 순이전 분포",
    unit: "day",
    category: "main-economy",
    dimensions: ["tier", "matchType"],
  },
  {
    key: "main.revenge_usage_rate",
    label: "Ranked 복수전 권리 대비 신청률",
    unit: "percent",
    category: "main-revenge",
  },
  {
    key: "main.integrity_hold_rate",
    label: "Ranked 경기 무결성 보류 비율",
    unit: "percent",
    category: "integrity",
    dimensions: ["reasonCode"],
  },
  {
    key: "main.sunday_cutoff_hold_count",
    label: "일요일 15시 Ranked 미정산 경기 보류 건수",
    unit: "count",
    category: "operations",
  },
  {
    key: "payback.recipient_rate",
    label: "페이백 수령자 비율",
    unit: "percent",
    category: "payback",
  },
  {
    key: "payback.payout_rate",
    label: "결제액 대비 실제 페이백 지급률",
    unit: "percent",
    category: "payback",
  },
  {
    key: "payback.band_distribution",
    label: "페이백 구간별 인원 분포",
    unit: "count",
    category: "payback",
    dimensions: ["ratePercent"],
  },
  {
    key: "payback.average_paid_attacks",
    label: "페이백 심사 이용자의 평균 일반 쟁탈전 완료 수",
    unit: "count",
    category: "payback",
  },
  {
    key: "payback.failure_reason_distribution",
    label: "페이백 미달 사유 분포",
    unit: "count",
    category: "payback",
    dimensions: ["reasonCode"],
  },
  {
    key: "weekly_mock.restriction_to_renewal_rate",
    label: "Matths 주간 공식 모의고사 제한 노출 후 재구매율",
    unit: "percent",
    category: "conversion",
  },
  {
    key: "match.active_defenders_by_tier",
    label: "티어별 활성 방어자 수",
    unit: "count",
    category: "match-liquidity",
    dimensions: ["division", "tier", "rankBucket"],
  },
  {
    key: "match.request_success_rate",
    label: "도전 신청 대비 매칭 성공률",
    unit: "percent",
    category: "match-liquidity",
    dimensions: ["division", "tier", "rankBucket"],
  },
  {
    key: "match.request_failure_reason_distribution",
    label: "매칭 실패 사유 분포",
    unit: "count",
    category: "match-liquidity",
    dimensions: [
      "division",
      "tier",
      "rankBucket",
      "reasonCode",
    ],
  },
  {
    key: "match.question_type_sample_count",
    label: "T등급·유형별 1대1 경기 표본 수",
    unit: "count",
    category: "question-calibration",
    dimensions: ["division", "difficultyTier", "defenderTier", "typeId", "policyVersion"],
  },
  {
    key: "match.defender_question_accuracy",
    label: "T등급·유형별 방어자 문항 정답률",
    unit: "percent",
    category: "question-calibration",
    dimensions: ["division", "difficultyTier", "defenderTier", "typeId", "policyVersion"],
  },
  {
    key: "match.challenger_question_accuracy",
    label: "T등급·유형별 도전자 문항 정답률",
    unit: "percent",
    category: "question-calibration",
    dimensions: ["division", "difficultyTier", "defenderTier", "typeId", "policyVersion"],
  },
  {
    key: "match.defender_challenger_accuracy_gap",
    label: "T등급별 방어자·도전자 정답률 차이",
    unit: "percent-point",
    category: "question-calibration",
    dimensions: ["division", "difficultyTier", "defenderTier", "policyVersion"],
  },
  {
    key: "match.perfect_score_rate",
    label: "T등급별 100점 경기 비율",
    unit: "percent",
    category: "question-calibration",
    dimensions: ["division", "difficultyTier", "policyVersion"],
  },
  {
    key: "match.zero_score_rate",
    label: "T등급별 무득점 경기 비율",
    unit: "percent",
    category: "question-calibration",
    dimensions: ["division", "difficultyTier", "policyVersion"],
  },
  {
    key: "match.complete_tie_rate",
    label: "T등급별 완전 동점 경기 비율",
    unit: "percent",
    category: "question-calibration",
    dimensions: ["division", "difficultyTier", "policyVersion"],
  },
]);

const FIRST_MONTH_ASSUMPTIONS = Object.freeze([
  {
    key: "simulation.challenger_win_rate",
    label: "공격자 승률 가정",
    value: 40,
    unit: "percent",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.unranked_challenger_refund_rate",
    label: "Unranked 공격자 승리 시 예치 점수 반환 비율",
    value: 100,
    unit: "percent",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_light_share",
    label: "저활동 이용자 비중 가정",
    value: 50,
    unit: "percent",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_regular_share",
    label: "중활동 이용자 비중 가정",
    value: 35,
    unit: "percent",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_heavy_share",
    label: "고활동 이용자 비중 가정",
    value: 15,
    unit: "percent",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_light_average_attacks",
    label: "저활동 이용자 평균 도전 수 가정",
    value: 2.5,
    unit: "count",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_regular_average_attacks",
    label: "중활동 이용자 평균 도전 수 가정",
    value: 7,
    unit: "count",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_heavy_average_attacks",
    label: "고활동 이용자 평균 도전 수 가정",
    value: 14,
    unit: "count",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_light_streak_probability",
    label: "저활동 이용자 30일 연속학습 확률 가정",
    value: 65,
    unit: "percent",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_regular_streak_probability",
    label: "중활동 이용자 30일 연속학습 확률 가정",
    value: 75,
    unit: "percent",
    minimumSampleSize: 100,
  },
  {
    key: "simulation.segment_heavy_streak_probability",
    label: "고활동 이용자 30일 연속학습 확률 가정",
    value: 85,
    unit: "percent",
    minimumSampleSize: 100,
  },
]);

module.exports = {
  FIRST_MONTH_ASSUMPTIONS,
  FIRST_MONTH_METRICS,
};
